server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container

      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream

      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service

      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: compose_project

      - source_labels: [__meta_docker_container_label_org_opencontainers_image_title]
        target_label: image

      - source_labels: [__meta_docker_container_label_traefik_enable]
        target_label: traefik_enabled

      - source_labels: [container]
        regex: 'drift-(post|search|analytics|tag)-service'
        target_label: layer
        replacement: app

      - source_labels: [container]
        regex: 'drift-(postgres|rabbitmq|meilisearch|ollama)'
        target_label: layer
        replacement: infra

      - source_labels: [container]
        regex: 'drift-(traefik)'
        target_label: layer
        replacement: gateway

      - source_labels: [container]
        regex: 'drift-(grafana|loki|promtail)'
        target_label: layer
        replacement: monitoring
